### ISSUE TITLE
Build only parameter fails

### ISSUE THREAD

**Issue by AngryProgrammerInside** [AshleyHow/WindowsOSBuild#2]
-BuildOnly parameter fails due to error on line 154 of WindowsOSBuild.psm1
Cause is the $Table member NoteProperty for "OS Build" is now "Build" after the update

eg it should be 
```PowerShell
($Table | Where-Object { $_ -Match "Version $OSVersion" } | Select-Object -First $LatestReleases)."Build"
```

**Comment by AshleyHow** [comment]
Thank you for reporting the issue. This has been fixed in v1.0.4 release of the module.
