### ISSUE TITLE
Not working on Server 2022 as expected

### ISSUE THREAD

**Issue by CarlosAmericano** [AshleyHow/WindowsOSBuild#3]
Unless im doing something really wrong, the Server 2022 is not working as intended, I think the main page doesnt provide the data for this OS.

PS C:\Windows\system32> Get-LatestOSBuild -OSName Server2022 -OSVersion 21H2 -LatestReleases 5

Version           : Version 21H2 (OS build 19044)
Servicing option  : LTSC • General Availability Channel
Availability date : 2021-11-22
Build             : 19044.1387
KB article        : KB5007253

Version           : Version 21H2 (OS build 19044)
Servicing option  : LTSC • General Availability Channel
Availability date : 2021-11-16
Build             : 19044.1288
KB article        : 

These are the details for the OS

PS C:\Windows\system32> $CurrentBuild
20348.350

PS C:\Windows\system32> $OSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      20348  0       

that can be found here
https://support.microsoft.com/en-us/topic/november-9-2021-kb5007205-os-build-20348-350-af102e6f-cc7c-4cd4-8dc2-8b08d73d2b31

**Comment by AshleyHow** [comment]
Apologies it was assumed that this was built off of the same codebase as win 10 win 20H2 like previous server releases (so same build numbers) however it seems that this is not the case. There is no table to query this information currently. This would mean major reworking of the code to query the page your refering too which I'd like to avoid currently. I'm going to see if I can reach out to Microsoft (social media, GitHub) to see if they will release a table on the release information page

**Comment by AshleyHow** [comment]
@CarlosAmericano new version released (v2112.1) to workaround this.

**Comment by CarlosAmericano** [comment]
@AshleyHow Thank you for that, appreciated 
Waiting for the main branch =)

**Comment by AshleyHow** [comment]
Dev has been merged into main.

**Comment by AshleyHow** [comment]
Server 2022 still not working due to missing function - apologies this will be fixed in 2112.2 release. Will running pester tests going forward prior to releasing to prevent this.

**Comment by AshleyHow** [comment]
Microsoft never decided to create the page so the work around will now stay permanent.
