### ISSUE TITLE
Whats the most simple way to detect if the Current OSBuild still gets security updates?

### ISSUE THREAD

**Issue by schittli** [AshleyHow/WindowsOSBuild#30]
Hello

**Thanks a lot for sharing your great work!**

Customers pay billions to Microsoft and in 2023, it's a shame that they do not offer a REST Service that offers this information.

I probably have a question about the most common use case:

### How can we tell until which date the current OS Build receives security updates?

In our days this information is very important and I suppose your WindowsOSBuild Module is a very good source of information for this question. But I don't know what information I have to interpret for this question to get a 100% sure answer.

Thanks a lot, kind regards,
Thomas

**Comment by schittli** [comment]
Good evening

# It looks like there is a bug...

## 1: Microsoft tells that Win10, 20H2 does no longer get updates:
https://learn.microsoft.com/en-us/windows/release-health/release-information
![image](https://github.com/AshleyHow/WindowsOSBuild/assets/8282673/8450532b-2dc5-4703-9d35-967e12b714e5)

## 2: But WindowsOSBuild explains, that Win10, 20H2 still gets updates:
```
Get-LatestOSBuild -OSName Win10 -OSVersion 20H2

Version           : Version 20H2 (OS build 19042)
Build             : 19042.2965
Availability date : 2023-05-09
Preview           : False
Out-of-band       : False
Servicing option  : Semi-Annual Channel
KB article        : KB5026361
KB URL            : https://support.microsoft.com/help/5026361
Catalog URL       : https://www.catalog.update.microsoft.com/Search.aspx?q=KB5026361
```

WindowsOSBuild should report for `Servicing option` something like `End of servicing` and not `Semi-Annual Channel`

Thanks a lot, kind regards,
Thomas

**Comment by AshleyHow** [comment]
Hi Tom,

I think you are confusing the servicing option with end of servicing
columns. I don't not consider this to be a bug. It is currently pulling the
'servicing option' as per table along with the latest Available update
correctly provided by Microsoft. I think  that column didn't exist when I
was creating this module years ago.

This module does not have the capability yet to state about end of
servicing, although it is something I would like to add. I'll see what I
can do.

**Comment by AshleyHow** [comment]
![image](https://github.com/AshleyHow/WindowsOSBuild/assets/28279067/19492f0f-f8a9-4b77-a075-e1bf92e5b61c)

**Comment by schittli** [comment]
Good evening @AshleyHow,

thanks a lot for your support!, I just saw your screenshot....

If users can use WindowsOSBuild to answer this not-so-simple question after calling the command with a clear `True` / `False`, **I think that's really great** and could help to protect users if the Windows Update once more fails.

Thanks a lot, kind regards,
Thomas

**Comment by AshleyHow** [comment]
In the end I decided to split this out to a different module.

Please see https://github.com/AshleyHow/WindowsOSServicing

Closing.
