### ISSUE TITLE
Get-LatestOSBuild -OSVersion "21H2" -OSName "Server2022" is broken

### ISSUE THREAD

**Issue by xenadmin** [AshleyHow/WindowsOSBuild#33]
Hi, since a few weeks, the OS Build query for Windows Server 2022 is broken. As far as I can tell, it reports the build number of Windows Server vNext (23H2) instead.

Example:
```
PS C:\Users\WDAGUtilityAccount> Get-LatestOSBuild -OSVersion "21H2" -OSName "Server2022"

Version           : Version 21H2 (OS build 25398)
Build             : 25398.531
Availability date : 2023-11-14
Preview           : False
Out-of-band       : False
Servicing option  : LTSC
KB article        : KB5032202
KB URL            : https://support.microsoft.com/en-us/help/5032202
Catalog URL       : https://www.catalog.update.microsoft.com/Search.aspx?q=KB5032202
```

The correct build number as of today would be: 20348.2113

Source for 2022: https://support.microsoft.com/en-us/topic/windows-server-2022-update-history-e1caa597-00c5-4ab9-9f3e-8212fe80b2ee
Source for 23H2: https://support.microsoft.com/en-us/topic/november-14-2023-kb5032202-os-build-25398-531-e1ee8019-47f8-4314-be67-32d4e48ac140

**Comment by AshleyHow** [comment]
Thanks for reporting this issue. Microsoft decided to introduce update history for this new server release into the same page for some reason. This is resolved in v2311.1, please update to the new release.
