### ISSUE TITLE
Issues with Server 2022 with Hotpatch enabled 

### ISSUE THREAD

**Issue by CarlosAmericano** [AshleyHow/WindowsOSBuild#35]
On Azure machines with hotpatch enabled this is not working.
https://support.microsoft.com/en-gb/topic/release-notes-for-hotpatch-in-azure-automanage-for-windows-server-2022-4e234525-5bd5-4171-9886-b475dabe0ce8

I tried and made something quick and dirty on our custom script to check if its autopatch or not and changing the url to be parsed

        ```
$hotpatchcheck = Get-HotFix -Id KB5003508 -ErrorAction SilentlyContinue
        if ($hotpatchcheck) {
            $URL = "https://support.microsoft.com/en-gb/topic/release-notes-for-hotpatch-in-azure-automanage-for-windows-server-2022-4e234525-5bd5-4171-9886-b475dabe0ce8"
        }
        Else {
            $URL = "https://support.microsoft.com/en-us/help/5005454"
        }
```

But even then, the webpage parse mechanism doesnt match what the OS reports

OS Build 20348.2091 --- correct info from the OS and correct info from the webpage body
OS Build 20346.2091 --- data pulled up from the module, and info from the table ?? 

Any ideas ?

**Comment by AshleyHow** [comment]
Happy to add support for hotpatch if can get it working, can you explain why a release is displaying two different builds though. I think it will be the problem here.

![image](https://github.com/AshleyHow/WindowsOSBuild/assets/28279067/6a32f877-c8d1-4a3f-a100-ebcf9a218ad9)

**Comment by CarlosAmericano** [comment]
That was my thoughts as well...what a mess.

We deploy a fair bit of servers in azure and for a couple of weeks / months autopatch enabled images are the default in azure.

Last month we didn't have any issues and looking at the logs from our rmm, it looks like the build number was the same for these images as a "normal" 2022 server. Only this month we noticed the check couldn't identify the osbuild to the windows server 2022 page and i tried to have a look.

As you mentioned, the build reported in the body of the page doesnt match what is on the table on the left, i can confirm that the info in the body is correct (at least for this months)
I also noticed that the links point to some weird hci server.

I tried to find other urls to parse and couldn't find anything, their docs are so bad regarding 2022 build versions...i think that the whole page of that autopatch is full of typos from a botched copy paste job.

**Comment by AshleyHow** [comment]
Raised as an issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/7633

Let's see what happens!

**Comment by AshleyHow** [comment]
Hot patch support coming shortly!

**Comment by CarlosAmericano** [comment]
Thank you for the improvement !

**Comment by AshleyHow** [comment]
2403.1 now released please test and feedback as I don't have access to a hotpatch enabled device to test.

**Comment by CarlosAmericano** [comment]
I think the next hotpatch release is going to be in May
https://support.microsoft.com/en-gb/topic/release-notes-for-hotpatch-in-azure-automanage-for-windows-server-2022-4e234525-5bd5-4171-9886-b475dabe0ce8

Ill keep an eye, thanks

**Comment by AshleyHow** [comment]
@CarlosAmericano just wondering how it went?

**Comment by CarlosAmericano** [comment]
Hello AshleyHow

That worked perfectly.. thank you!!
